// ============================================================
// 員工帳號（預設登入帳號）
// ============================================================
export const ACCOUNTS = [
  { id: 'N001', name: '李雅婷', role: 'nurse',    password: '1234' },
  { id: 'N002', name: '張志明', role: 'nurse',    password: '1234' },
  { id: 'D001', name: '王建國', role: 'doctor',   password: '1234' },
  { id: 'D002', name: '林美玲', role: 'doctor',   password: '1234' },
  { id: 'S001', name: '陳大偉', role: 'security', password: '1234' },
]

// ============================================================
// 平面圖區域定義（對應 SVG FloorMap 座標系）
// viewBox="0 0 900 580"
// ============================================================
export const FLOOR_AREAS = [
  { id: 'pediatric',     name: '小兒科急診看診區', en: 'Pediatric Emergency',          cx: 100, cy: 175 },
  { id: 'emergency_icu', name: '急診-重症區',       en: 'Emergency & Intensive Care',   cx: 370, cy:  80 },
  { id: 'treatment',     name: '診療區',             en: 'Treatment Area',               cx: 270, cy: 222 },
  { id: 'observation',   name: '留觀區',             en: 'Observation Area',             cx: 450, cy: 222 },
  { id: 'clinical',      name: '臨床處置區',         en: 'Clinical Treatment Area',      cx: 105, cy: 395 },
  { id: 'ct_room',       name: '電腦斷層室',         en: 'CT Room',                      cx: 285, cy: 365 },
  { id: 'fluoroscopy',   name: '透視攝影室',         en: 'Fluoroscopy Rm.',              cx: 460, cy: 365 },
  { id: 'xray',          name: 'X光室',              en: 'X-Ray Rm.',                    cx: 285, cy: 475 },
  { id: 'angiography',   name: '血管攝影室',         en: 'Angiography Rm.',              cx: 460, cy: 475 },
  { id: 'mri',           name: '核磁共振室',         en: 'Nuclear MRI Chamber',          cx: 720, cy: 450 },
  { id: 'exit',          name: '醫院出口',           en: 'Hospital Exit',                cx: 450, cy: 560 },
]

// ============================================================
// 特殊病人分類
// ============================================================
export const CATEGORY_CONFIG = {
  dementia:    { label: '失智',   color: 'bg-purple-100 text-purple-800 border-purple-300', dot: '#7c3aed', urgent: true  },
  pediatric:   { label: '小兒',   color: 'bg-sky-100 text-sky-800 border-sky-300',          dot: '#0284c7', urgent: true  },
  psychiatric: { label: '身心科', color: 'bg-amber-100 text-amber-800 border-amber-300',    dot: '#d97706', urgent: true  },
  normal:      { label: '一般',   color: 'bg-slate-100 text-slate-600 border-slate-300',    dot: '#475569', urgent: false },
}

// ============================================================
// 初始病人資料
// ============================================================
export const PATIENTS_INITIAL = [
  {
    id: 'E001',
    name: '王大同',
    age: 73,
    gender: '男',
    category: 'dementia',
    areaId: 'observation',
    areaName: '留觀區',
    bedNumber: '觀2',
    condition: '穩定觀察中',
    status: 'in_hospital',   // in_hospital | left_hospital
    leftHospitalTime: null,
    assignedNurse: 'N001',
    assignedDoctor: 'D001',
    callActive: false,
    markerX: 460,
    markerY: 210,
  },
  {
    id: 'E002',
    name: '林小芸',
    age: 5,
    gender: '女',
    category: 'pediatric',
    areaId: 'pediatric',
    areaName: '小兒科急診看診區',
    bedNumber: '小兒3',
    condition: '發燒觀察',
    status: 'in_hospital',
    leftHospitalTime: null,
    assignedNurse: 'N001',
    assignedDoctor: 'D002',
    callActive: false,
    markerX: 105,
    markerY: 165,
  },
  {
    id: 'E003',
    name: '陳建志',
    age: 45,
    gender: '男',
    category: 'psychiatric',
    areaId: 'clinical',
    areaName: '臨床處置區',
    bedNumber: '處3',
    condition: '情緒不穩定',
    status: 'in_hospital',
    leftHospitalTime: null,
    assignedNurse: 'N002',
    assignedDoctor: 'D001',
    callActive: false,
    markerX: 105,
    markerY: 390,
  },
  {
    id: 'E004',
    name: '張美華',
    age: 58,
    gender: '女',
    category: 'normal',
    areaId: 'treatment',
    areaName: '診療區',
    bedNumber: '診2',
    condition: '等候檢查',
    status: 'in_hospital',
    leftHospitalTime: null,
    assignedNurse: 'N001',
    assignedDoctor: 'D001',
    callActive: false,
    markerX: 270,
    markerY: 215,
  },
  {
    id: 'E005',
    name: '李浩然',
    age: 32,
    gender: '男',
    category: 'normal',
    areaId: 'ct_room',
    areaName: '電腦斷層室',
    bedNumber: 'CT1',
    condition: '進行CT掃描',
    status: 'in_hospital',
    leftHospitalTime: null,
    assignedNurse: 'N002',
    assignedDoctor: 'D002',
    callActive: false,
    markerX: 285,
    markerY: 358,
  },
  {
    id: 'E006',
    name: '吳淑芬',
    age: 66,
    gender: '女',
    category: 'normal',
    areaId: 'emergency_icu',
    areaName: '急診-重症區',
    bedNumber: '重1',
    condition: '重症監控中',
    status: 'in_hospital',
    leftHospitalTime: null,
    assignedNurse: 'N002',
    assignedDoctor: 'D001',
    callActive: false,
    markerX: 370,
    markerY: 72,
  },
  {
    id: 'E007',
    name: '黃文凱',
    age: 78,
    gender: '男',
    category: 'dementia',
    areaId: 'exit',
    areaName: '醫院外部',
    bedNumber: 'MRI2',
    condition: '已離開醫院',
    status: 'left_hospital',
    leftHospitalTime: new Date(Date.now() - 25 * 60 * 1000),
    assignedNurse: 'N001',
    assignedDoctor: 'D002',
    callActive: false,
    markerX: 450,
    markerY: 550,
  },
  {
    id: 'E008',
    name: '方淑真',
    age: 12,
    gender: '女',
    category: 'pediatric',
    areaId: 'fluoroscopy',
    areaName: '透視攝影室',
    bedNumber: '透1',
    condition: '進行透視檢查',
    status: 'in_hospital',
    leftHospitalTime: null,
    assignedNurse: 'N002',
    assignedDoctor: 'D002',
    callActive: false,
    markerX: 460,
    markerY: 358,
  },
]
